# AWS properties
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION:us-east-1}
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID}
    app-client-id: ${COGNITO_APP_CLIENT_ID}
    app-client-secret: ${COGNITO_APP_CLIENT_SECRET}

spring:
  profiles:
    include: dev
  cloud:
    consul:
      host: ${REGISTRY_HOST:localhost}
      port: ${REGISTRY_PORT:8500}
      discovery:
        enabled: true
        prefer-ip-address: true
        health-check-interval: 1s
        health-check-path: /actuator/health
        service-name: ${spring.application.name}
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${spring.cloud.aws.cognito.issuer-uri}
#          jwk-set-uri: ${spring.cloud.aws.cognito.jwk-set-uri}

management:
  endpoints:
    web:
      exposure:
        include: "*" # refresh, bus-refresh, beans, env
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

# Setting the logging levels for the service
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        cloud:
          bootstrap: ERROR
      hibernate:
        persister.entity: ERROR
      apache:
        kafka: ERROR
    nl:
      basjes:
        parse:
          useragent: ERROR
    com:
      vladmihalcea: ERROR
    io:
      github:
        openfeign: ERROR