spring:
  cloud:
      gateway:
        httpclient:
          connect-timeout: 5000
          response-timeout: 30s
          pool:
            type: elastic
            max-idle-time: 15s
            max-life-time: 60s
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
            predicates:
              - name: Path
                args:
                  pattern: "'/api/' + serviceId + '/**'"

            filters:
              - name: CircuitBreaker
                args:
                  name: serviceId
                  fallbackUri: "'forward:/fallback'"
        default-filters:
          - StripPrefix=2
          - name: Retry
            args:
              retries: 3
              methods: GET
              series: SERVER_ERROR
              exceptions: java.io.IOException, java.util.concurrent.TimeoutException
              backoff:
                firstBackoff: 50ms
                maxBackOff: 500ms
                factor: 2
                basedOnPreviousValue: false