server:
  port: ${PORT:0}
  servlet:
    context-path: /api

spring:
  application:
    name: auth-service
  cloud:
    consul:
      host: localhost
      port: 8500

# AWS properties
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID}
    app-client-id: ${COGNITO_APP_CLIENT_ID}
    app-client-secret: ${COGNITO_APP_CLIENT_SECRET}